const ADMIN_USERNAME = 'khalilnahhat';

const defaultLiveSessions = [
  {
    externalId: 'live-session-01',
    track: 'Midnight Drive',
    duration: '06:42',
    genre: 'House',
    language: 'Instrumental',
  },
  {
    externalId: 'live-session-02',
    track: 'Velvet Pressure',
    duration: '05:18',
    genre: 'Tech House',
    language: 'English',
  },
  {
    externalId: 'live-session-03',
    track: 'Signal Rouge',
    duration: '07:04',
    genre: 'Melodic Techno',
    language: 'French',
  },
  {
    externalId: 'live-session-04',
    track: 'Afterlight Pulse',
    duration: '04:56',
    genre: 'Progressive House',
    language: 'Instrumental',
  },
  {
    externalId: 'live-session-05',
    track: 'Room Theory',
    duration: '05:37',
    genre: 'Open Format',
    language: 'Arabic / English',
  },
];

const defaultArchiveItems = [
  {
    externalId: 'archive-01',
    title: 'Control Booth',
    category: 'Live',
    location: 'TORONTO',
    date: 'APR 2026',
    mediaType: 'Photo',
    image: 'asset:archive-live',
    alt: 'Dark stage placeholder showing a performance setup and control console.',
  },
  {
    externalId: 'archive-02',
    title: 'Portrait Study',
    category: 'Portrait',
    location: '[CITY]',
    date: 'MAY 2026',
    mediaType: 'Photo',
    image: 'asset:archive-portrait',
    alt: 'Monochrome portrait placeholder framed in an editorial layout.',
  },
  {
    externalId: 'archive-03',
    title: 'Room Response',
    category: 'Crowd',
    location: 'MONTRÉAL',
    date: 'JUN 2026',
    mediaType: 'Photo',
    image: 'asset:archive-crowd',
    alt: 'Abstract crowd placeholder with layered silhouettes and stage lighting.',
  },
  {
    externalId: 'archive-04',
    title: 'Motion Scan',
    category: 'Motion',
    location: 'VANCOUVER',
    date: 'JUN 2026',
    mediaType: 'Video still',
    image: 'asset:archive-motion',
    alt: 'Motion-focused placeholder with diagonal light streaks.',
  },
  {
    externalId: 'archive-05',
    title: 'Load-in Detail',
    category: 'Live',
    location: 'OTTAWA',
    date: 'FEB 2026',
    mediaType: 'Photo',
    image: 'asset:archive-live',
    alt: 'Editorial live placeholder showing venue detail panels and stage structure.',
  },
  {
    externalId: 'archive-06',
    title: 'Afterhours Frame',
    category: 'Portrait',
    location: '[LOCATION]',
    date: 'JUL 2026',
    mediaType: 'Photo',
    image: 'asset:archive-portrait',
    alt: 'Portrait placeholder with dark tonal treatment and minimal red accents.',
  },
  {
    externalId: 'archive-07',
    title: 'Peak Window',
    category: 'Crowd',
    location: 'TORONTO',
    date: 'JUL 2026',
    mediaType: 'Photo',
    image: 'asset:archive-crowd',
    alt: 'Crowd placeholder featuring layered figures and a kinetic red signal line.',
  },
  {
    externalId: 'archive-08',
    title: 'Signal Trails',
    category: 'Motion',
    location: '[CITY]',
    date: 'AUG 2026',
    mediaType: 'Video still',
    image: 'asset:archive-motion',
    alt: 'Abstract motion placeholder with diagonal red and white streaks.',
  },
];

const defaultLiveStreamConfig = {
  key: 'primary',
  isLive: false,
  title: 'Khalil Nahhat Live DJ Session',
  streamUrl: '',
  posterImage: '',
  statusLabel: 'Offline until Khalil starts the next OBS stream.',
  muxLiveStreamId: '',
  muxPlaybackId: '',
  muxStreamKey: '',
  muxRtmpUrl: 'rtmps://global-live.mux.com:443/app',
};

module.exports = {
  ADMIN_USERNAME,
  defaultArchiveItems,
  defaultLiveSessions,
  defaultLiveStreamConfig,
};
